### ISSUE TITLE
Python 2 Required

### ISSUE THREAD

**Issue by MortalCatalyst** [cssanimation/gulp-sass-starter#6]
Why is Python 2 a requirement to install gulp and sass? 

On windows 10 Python 2 fails as a requirement, is there a way to avoid needing to build with a now obsolete language version?

```python
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\sayth\projects\Learn_CSS\starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:166:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at C:\\Users\\sayth\\projects\\Learn_CSS\\starter\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
```

**Comment by MortalCatalyst** [comment]
Closed because not your issue. Not resolved but clearly an issue with gyp, node-sass and windows.

for reference [gyp](https://github.com/nodejs/node-gyp/issues/1977)
fsevents [fsevents unsupported arch](https://github.com/angular/angular/issues/13935)
and haven't figured out how to solve the node-sass issue yet.
